name: teste unitarios python
on: 
  push:
    branch: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  teste-python:
    runs-on: ubuntu-latest

    steps:
      - name: checkout project
        uses: actions/checkout@v2
       
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e pytest
          pip install -e -r requirements.txt;

      - name: Test with pytest
        run: |
          pytest